### ISSUE TITLE
how to do y normalization  

### ISSUE THREAD

**Issue by janursa** [janursa/geneRNI#17]

**Comment by AntoinePassemiers** [comment]
Fixed. y is now normalised inside the `GeneEstimator` class and the predictions of the latter are unnormalised so everything outside the class ignores about the normalization

**Comment by AntoinePassemiers** [comment]
https://github.com/janursa/geneRNI/blob/a5d803d2e143dafe5443594e1d5d0bfb6ecc3d2b/geneRNI/core.py#L159
https://github.com/janursa/geneRNI/blob/a5d803d2e143dafe5443594e1d5d0bfb6ecc3d2b/geneRNI/core.py#L182
https://github.com/janursa/geneRNI/blob/a5d803d2e143dafe5443594e1d5d0bfb6ecc3d2b/geneRNI/core.py#L191
