### ISSUE TITLE
inferred links needs normalization before inference?

### ISSUE THREAD

**Issue by janursa** [janursa/geneRNI#18]

**Comment by AntoinePassemiers** [comment]
Let's provide basic algorithms to normalize score matrices, like average product correction or row/column weighting

**Comment by AntoinePassemiers** [comment]
Function `network_inference` now has two new parameters `grn_normalization` and `grn_correction` to remove biases.

**Comment by janursa** [comment]
i dont see these params in the updated code. have you pushed it?

**Comment by AntoinePassemiers** [comment]
Yes I pushed it

https://github.com/janursa/geneRNI/blob/a5d803d2e143dafe5443594e1d5d0bfb6ecc3d2b/geneRNI/core.py#L46
