### ISSUE TITLE
Relevance of mixing static and dynamic data

### ISSUE THREAD

**Issue by AntoinePassemiers** [janursa/geneRNI#23]
I have an existential problem with the fact of simply concatenating static data with time series, as the target values `y` do not have the same meaning nor value ranges.

- In static settings, `y` values represent protein/mRNA concentrations
- In time series, after preprocessing (with the lambda functions) the `y` values represent change rates.

These different data types are drastically different by nature (e.g. it can be negative in the second case). Did they mix static and dynamic data in dynGENIE? If not, I think we should brainstorm about a way to fix this.

**Comment by janursa** [comment]
Yes, the culture of mixing them comes from dynGENIE3. 
You are correct, there should be a better way. Also, the fact that we combine static and dynamic data, with decay_coeff accounted for the former and not the latter, is not realistic. We should indeed think of how to fix this problem more basically

**Comment by AntoinePassemiers** [comment]
Didn't know they mixed the data. I'll go back to their publication to see how (whether) they addressed that concern.

**Comment by AntoinePassemiers** [comment]
The simplest approach (for the moment) could be to do standard-scaling for static and dynamic data separately. But not sure this would be of any help since the targets will still have completely different meanings.

**Comment by AntoinePassemiers** [comment]
Or we redesign our models into **multivariate** models that jointly predict gene expression and gene expression derivative:
- For neural networks, that's straightforward
- For linear models, this is equivalent to training 2 separate models
- For tree-based models, there are solutions in the literature but I'm not sure whether there is an off-the-shelf implementation anywhere

**Comment by AntoinePassemiers** [comment]
Solved, as mentioned in #25
