### ISSUE TITLE
potantial problem with GRN adjacency matrix 

### ISSUE THREAD

**Issue by janursa** [janursa/geneRNI#28]
there might be a problem with the normalization of the links:
https://github.com/janursa/geneRNI/blob/c0c172d86d12fbc0a410b9549470d8517ffaef58/geneRNI/core.py#L93

this produces the passive sum to be always 1. Passive sum is defined as the sum of the regulatory wights of the rest of the proteins on protein i.

For now, i deactivated this line. Before pushing this as a new commit, there should be a unit test to evaluate this problem

**Comment by AntoinePassemiers** [comment]
Why commenting out this block when you could simply set `grn_normalization` to False?

There is no problem with the code _per se_, but I would hypothesize that your GRN is too small compared to the networks most people are usually working with.

**Comment by AntoinePassemiers** [comment]
Btw the purpose of the normalisation was precisely to constrain each column to sum up to 1, so nothing surprising here

**Comment by janursa** [comment]
can we use a different normalization method? can you specify again why do we need this normalization?

**Comment by AntoinePassemiers** [comment]
We can propose different normalization methods and let the end-user pick which one they want, or whether they want it (like I did for the bias correction).

We may need normalization to account for the differences between the estimators, especially if you hyper-optimize each estimator separately.

Example: if estimator `i` is a linear model with strong L1 regularisation, and estimator `j` has lower regularisation, you will see artificially more zeros in column `i` of your adjacency matrix than in column `j`. If you use L2 regularisation, you will simply see differences in the scaling of the column.

Of course normalisation can still overcorrect your matrix, but this is mostly the case if your matrix is very small. So let's assume other people might use geneRNI for small GRNs, and set the parameter to `False` by default?

**Comment by AntoinePassemiers** [comment]
Based on the live discussion we had, I think that instead of normalizing columns there, it would be preferrable to do model-specific corrections at the level of the estimators' implementation, by adding one extra abstract method to the base class:

https://github.com/janursa/geneRNI/blob/c0c172d86d12fbc0a410b9549470d8517ffaef58/geneRNI/models/base.py#L28

I feel like for linear models it should be easy. I'll have to do some experiments to be sure

**Comment by AntoinePassemiers** [comment]
My previous message should go to issue #29 actually.

**Comment by AntoinePassemiers** [comment]
Matrix normalization has been removed
